version: '3.8' # Compose version

services:
  postgres:
    image: bitnami/postgresql:16.4.0 # Bitnami PostgreSQL image
    container_name: sge_rest_api_db # Container name
    environment:
      - POSTGRESQL_USERNAME=docker # PostgreSQL username
      - POSTGRESQL_PASSWORD=docker # PostgreSQL user password
      - POSTGRESQL_DATABASE=sge_rest # Database name
      - ALLOW_EMPTY_PASSWORD=no # Don't allow empty password
    ports:
      - '5432:5432' # Ports mapping (host:container)
    volumes:
      - sge_rest_api_data:/bitnami/postgresql # Data persistence

volumes:
  sge_rest_api_data: # Volume for data persistence
