### GET all alunos 

GET http://localhost:8000/alunos?page_size=2&cursor=2

### GET aluno

GET http://localhost:8000/alunos/3


### Create a aluno
POST http://localhost:8000/alunos/create
Content-Type: application/json

{
    "nomeCompleto": "Nome de exemplo",
    "nomeCompletoPai": "Nome do pai exemplo",
    "nomeCompletoMae": "Nome da mãe exemplo",
    "numeroBi": "000000001CA000",
    "dataNascimento": "2001-01-19",
    "genero": "M"
}

### Update an existent aluno
PUT http://localhost:8000/alunos/2
Content-Type: application/json

{
    "nomeCompleto": "Teste UPDATED",
    "nomeCompletoPai": "Teste UPDATED",
    "nomeCompletoMae": "Teste UPDATED",
    "dataNascimento": "2001-01-19",
    "genero": "F"
}