### GET all alunos 

GET http://localhost:8000/api/alunos?page_size=2

### GET aluno

GET http://localhost:8000/api/alunos/2

### Create a aluno
POST http://localhost:8000/api/alunos/create
Content-Type: application/json

{
    "nomeCompleto": "Mateus Vale Celestino Nelito",
    "nomeCompletoPai": "Nelito Cassule Toquessa",
    "nomeCompletoMae": "Ana Vale João",
    "numeroBi": "000000000LA000",
    "dataNascimento": "2005-06-01",
    "genero": "M",
    "bairro": "Simeone Mucune",
    "rua": "4 de Abril",
    "numeroCasa": 15,
    "telefone": "955555500",
    "email": "email@example.com",
    "responsaveis": [
      {
        "nomeCompleto": "Nelito Cassule Toquessa",
        "parentescoId": 1,
        "bairro": "Rocha",
        "rua": "Desconhecida",
        "numeroCasa": 105,
        "telefone": "932879871"
      },
            {
        "nomeCompleto": "Ana Vale João",
        "parentescoId": 2,
        "bairro": "Simeone Mucune",
        "rua": "4 de Abril",
        "numeroCasa": 15,
        "telefone": "936666123"
      }
    ]
}

### Update an existent aluno
PUT http://localhost:8000/api/alunos/2
Content-Type: application/json

{
    "nomeCompleto": "UPDATED FIRST",
    "nomeCompletoPai": "UPDATED FIRST",
    "nomeCompletoMae": "UPDATED FIRST",
    "dataNascimento": "2001-01-19",
    "genero": "M",
    "bairro": "Camama",
    "rua": "3 Bancadas",
    "numeroCasa": 10,
    "telefone": "932623102",
    "email": "aswss@exmle.co"
}