### GET all alunos
GET http://localhost:8000/api/alunos?page_size=2

### GET aluno
GET http://localhost:8000/api/alunos/1

### Update an existent aluno
PUT http://localhost:8000/api/alunos/1
Content-Type: application/json

{
  "nomeCompleto": "UPDATED Vale Celestino Nelito",
  "nomeCompletoPai": "Nelito Cassule Toquessa",
  "nomeCompletoMae": "Ana Vale João",
  "dataNascimento": "2005-06-01",
  "genero": "M",
  "endereco": {
    "bairro": "Simeone Mucune",
    "rua": "4 de Abril",
    "numeroCasa": 7
  },
  "contacto": {
    "telefone": "925555500",
    "email": "asasa@asa.new"
  }
}

### GET all responsaveis
GET http://localhost:8000/api/alunos/1/responsaveis

### Create Responsavel to Aluno
POST http://localhost:8000/api/alunos/1/responsaveis
Content-Type: application/json

{
  "nomeCompleto": "Teste Da Silva",
  "parentescoId": 3,
  "endereco": {
    "bairro": "Cazenga",
    "rua": "Dos Matadores",
    "numeroCasa": 10
  },
  "contacto": {
    "telefone": "939556784",
    "email": "teste@email.com",
    "outros": "blah blah blah"
  }
}

### GET all matriculas
GET http://localhost:8000/api/alunos/1/matriculas