### GET all alunos 

GET http://localhost:8000/api/alunos?page_size=2

### GET aluno

GET http://localhost:8000/api/alunos/2

### Create a aluno
POST http://localhost:8000/api/alunos/create
Content-Type: application/json

{
    "nomeCompleto": "",
    "nomeCompletoPai": "",
    "nomeCompletoMae": "",
    "numeroBi": "000000001MA000",
    "dataNascimento": "2001-01-19",
    "genero": "M",
    "bairro": "",
    "rua": "",
    "numeroCasa": 0,
    "telefone": "9xxxxxxxx",
    "email": "email@example.com"
}

### Update an existent aluno
PUT http://localhost:8000/api/alunos/2
Content-Type: application/json

{
    "nomeCompleto": "UPDATED FIRST",
    "nomeCompletoPai": "UPDATED FIRST",
    "nomeCompletoMae": "UPDATED FIRST",
    "dataNascimento": "2001-01-19",
    "genero": "M",
    "bairro": "Camama",
    "rua": "3 Bancadas",
    "numeroCasa": 10,
    "telefone": "932623102",
    "email": "aswss@exmle.co"
}