### GET all alunos 

GET http://localhost:8000/alunos
Content-Type: application/json

### Create a aluno
POST http://localhost:8000/alunos/create
Content-Type: application/json

{
    "nomeCompleto": "Nome de exemplo",
    "nomeCompletoPai": "Nome do pai exemplo",
    "nomeCompletoMae": "Nome da mãe exemplo",
    "numeroBi": "000000000CA000",
    "dataNascimento": "2001-01-19",
    "genero": "M"
}