### Create
POST http://localhost:8000/api/ano-lectivos
Content-Type: application/json

{
  "inicio": "2024-09-01",
  "termino": "2025-08-01"
}

### Update
PUT http://localhost:8000/api/ano-lectivos/1
Content-Type: application/json

{
  "inicio": "2023-09-01",
  "termino": "2024-08-01"
}

### Get all
GET http://localhost:8000/api/ano-lectivos

### Get unique
GET http://localhost:8000/api/ano-lectivos/1

### Get all classes
GET http://localhost:8000/api/ano-lectivos/1/classes

### Create classe in ano lectivo
POST http://localhost:8000/api/ano-lectivos/1/classes
Content-Type: application/json

{
  "nome": "10ª",
  "cursoId": 1
}