### Create
POST http://localhost:8000/api/classes
Content-Type: application/json

{
  "nome": "12ª",
  "ordem": 3,
  "cursoId": 1,
  "valorMatricula": 3000,
  "disciplinas": [
    1, 2
  ]
}

### Update
PUT http://localhost:8000/api/classes/4
Content-Type: application/json

{
  "nome": "13ª",
  "cursoId": 1,
  "valorMatricula": 3000
}

### Get Unique
GET http://localhost:8000/api/classes/1

### Get Classe 
GET http://localhost:8000/api/classes?cursoId=2

### Get Classe Turmas
GET http://localhost:8000/api/classes/1/turmas

### Get Classe Alunos
GET http://localhost:8000/api/classes/3/alunos

### Get Classe Disciplinas
GET http://localhost:8000/api/classes/3/disciplinas

### Post Classe Disciplinas
POST http://localhost:8000/api/classes/3/disciplinas
Content-Type: application/json

{
  "disciplinas": [
    1, 2
  ]
}

### Create Turma in Classe
POST http://localhost:8000/api/classes/1/turmas
Content-Type: application/json

{
  "nome": "C",
  "salaId": 1,
  "turnoId": 1
}