### Create
POST http://localhost:8000/api/classes
Content-Type: application/json

{
  "nome": "12ª",
  "cursoId": 1,
  "valorMatricula": 3000
}

### Update
PUT http://localhost:8000/api/classes/4
Content-Type: application/json

{
  "nome": "13ª",
  "cursoId": 1,
  "valorMatricula": 3000
}

### Get Unique
GET http://localhost:8000/api/classes/1

### Get Classe Turmas
GET http://localhost:8000/api/classes/1/turmas

### Get Classe Alunos
GET http://localhost:8000/api/classes/3/alunos

### Create Turma in Classe
POST http://localhost:8000/api/classes/1/turmas
Content-Type: application/json

{
  "nome": "C",
  "salaId": 1,
  "turnoId": 1
}