### Create a disciplina for a especific curso
POST http://localhost:8000/api/disciplinas/create
Content-Type: application/json

{
    "nome": "Língua Portuguesa",
    "descricao": "Estuda a língua nativa Angolana"
}

### UPDATE an existent disciplina
PUT http://localhost:8000/api/disciplinas/1
Content-Type: application/json

{
    "nome": "Matemática",
    "descricao": "Ciência exata"
}

### GET a disciplina details
GET http://localhost:8000/api/disciplinas/1

### GET disciplinas
GET http://localhost:8000/api/disciplinas

### Associate some disciplina to multiples cursos
POST http://localhost:8000/api/disciplinas/4/cursos
Content-Type: application/json

{
    "cursos": [1, 2, 3]
}