### GET all parentescos 
GET http://localhost:8000/api/parentescos

### GET parentesco
GET http://localhost:8000/api/parentescos/1

### Create a parentesco
POST http://localhost:8000/api/parentescos/create
Content-Type: application/json

{
    "nome": "Pai"
}

### Update an existent parentesco
PUT http://localhost:8000/api/parentescos/3
Content-Type: application/json

{
    "nome": "Irmão"
}