### Create a professor
POST http://localhost:8000/api/professores/create
Content-Type: application/json

{
    "nomeCompleto": "Nome Completo",
    "dataNascimento": "2005-09-10",
    "telefone": "923923123",
    "email": "emil@exampe.com",
    "outros": "tel. alternativo: 99800123"
}

### Update an existent professor
PUT http://localhost:8000/api/professores/1
Content-Type: application/json

{
    "nomeCompleto": "Nome Completo",
    "dataNascimento": "2005-09-10",
    "telefone": "933123123",
    "email": "emal@example.com",
    "outros": "tel. alternativo: 998000123"
}

### GET a professor by id
GET http://localhost:8000/api/professores/1

### GET all professores
GET http://localhost:8000/api/professores