### Create a professor
POST http://localhost:8000/api/professores/create
Content-Type: application/json

{
    "nomeCompleto": "Mateus Nelito",
    "dataNascimento": "2005-09-10",
    "telefone": "935580500",
    "email": "emaiyil@example.com",
    "outros": "tel. alternativo: 99800123",
    "disciplinas": [1, 2, 3]
}

### Update an existent professor
PUT http://localhost:8000/api/professores/1
Content-Type: application/json

{
    "nomeCompleto": "Nome Completo",
    "dataNascimento": "2005-09-10",
    "telefone": "933123123",
    "email": "emal@example.com",
    "outros": "tel. alternativo: 998000123"
}

### GET a professor by id
GET http://localhost:8000/api/professores/1

### GET all professores
GET http://localhost:8000/api/professores?page_size=2

### Associate some professor to multiples disciplinas
POST http://localhost:8000/api/professores/7/disciplinas
Content-Type: application/json

{
    "disciplinas": [1, 2, 3]
}

### Delete a professor and disciplina association
DELETE http://localhost:8000/api/professores/8/disciplinas/1