### Create a professor
POST http://localhost:8000/api/professores
Content-Type: application/json

{
    "nomeCompleto": "Mateus Nelito",
    "dataNascimento": "2005-09-10",
    "contacto": {
        "telefone": "935580500",
        "email": "emaiyil@example.com",
        "outros": "tel. alternativo: 99800123"
    },
    "disciplinas": [1]
}

### Update an existent professor
PUT http://localhost:8000/api/professores/1
Content-Type: application/json

{
    "nomeCompleto": "UPDATED FIRST",
    "dataNascimento": "2005-09-10",
    "contacto": {
        "telefone": "935580500",
        "email": "emaiyil@example.com",
        "outros": "tel. alternativo: 99800123"
    }
}

### GET a professor by id
GET http://localhost:8000/api/professores/1

### GET all professores
GET http://localhost:8000/api/professores?page_size=2

### Associate some professor to multiples disciplinas
POST http://localhost:8000/api/professores/1/disciplinas
Content-Type: application/json

{
    "disciplinas": [1]
}

### Delete a professor and disciplina association
DELETE http://localhost:8000/api/professores/1/disciplinas/1

### Delete some disciplinas associated with especific professor
DELETE http://localhost:8000/api/cursos/1/disciplinas
Content-Type: application/json

{
    "disciplinas": [1]
}

### Create association between professor and classe
POST http://localhost:8000/api/professores/2/classes
Content-Type: application/json

{
  "disciplinaId": 3,
  "classeId": 2,
  "turmaId": 2
}

### Get classes associated with professor
GET http://localhost:8000/api/professores/1/classes