### GET responsavel
GET http://localhost:8000/api/responsaveis/1

### Update an existent responsavel
PUT http://localhost:8000/api/responsaveis/1
Content-Type: application/json

{
  "nomeCompleto": "UPDATED FIRST",
  "parentescoId": 4,
  "endereco": {
    "bairro": "Camama",
    "rua": "Três Bancadas",
    "numeroCasa": 50
  },
  "contacto": {
    "telefone": "935555500"
  }
}

### Delete an existent responsavel
DELETE http://localhost:8000/api/responsaveis/1